version: '3.8'

services:
  insurance-pdf-extractor:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENVIRONMENT=production
      - LOG_LEVEL=INFO
      # Add your API keys here or use .env file
      - GEMINI_API_KEY=${GEMINI_API_KEY:-}
      - API_KEY=${API_KEY:-your-secure-api-key-here}
      - DEFAULT_MODEL=gemini-1.5-flash
      - MAX_FILE_SIZE_MB=50
      - RATE_LIMIT_REQUESTS=100
    volumes:
      # Persist data and logs
      - pdf_data:/app/data
      - pdf_logs:/app/logs
      # Mount config files for easy updates (optional)
      - ./config:/app/config:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health/live"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy for production
  # nginx:
  #   image: nginx:alpine
  #   ports:
  #     - "80:80"
  #     - "443:443"
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #   depends_on:
  #     - insurance-pdf-extractor
  #   restart: unless-stopped

volumes:
  pdf_data:
    driver: local
  pdf_logs:
    driver: local