default_version: "v1"

versions:
  v1:
    description: "Workers Compensation extraction with focus on owners-officers exclusion"
    template: |
      From the provided insurance quote PDF, extract the listed fields for the Workers' Compensation policy. Return the results in the form of a JSON object, as shown in the example output.
      Each field should adhere to the specified data type and description. Follow the example structure provided.

      ### Fields to Extract:

      {fields}

      ### Example Output:

      {example_output}

    example_output: |
      {Ø
        "quote_number": "01WECBA3BVG003",
        "policy_effective_date": "09/19/2023",
        "policy_expiration_date": "09/19/2024",
        "named_insured_name": "ACME BEER II LLC DBA: NORTH END PIZZA",
        "named_insured_address": "1513 N 13TH ST BOISE ID 83702",
        "additional_named_insured_name": "Excluded",
        "additional_named_insured_address": "Excluded",
        "issuing_carrier": "['TX - Hartford Casualty Insurance Company - 3500', 'PA - Hartford Casualty Insurance Company - 253']",
        "commission": "EMPTY VALUE",
        "estimated_premium_amount": "3753",
        "minimum_earned_premium": "EMPTY VALUE",
        "taxes": "EMPTY VALUE",
        "tria": "Included",
        "waiver_of_subrogation_type": "Excluded",
        "workers_comp_each_accident_limit": "1000000",
        "workers_comp_disease_each_employee": "1000000",
        "workers_comp_disease_policy_limit": "1000000",
        "workers_comp_exclusion_description": "ID-Excluded"
      }
